### ISSUE TITLE
Collection: Improve Support for multi-monitor setups

### ISSUE THREAD

**Issue by Samuel12321** [ModernFlyouts-Community/ModernFlyouts#736]
- [ ] Feature Request: Dynamic Monitor Choosing #672

> Flyout appears on secondary monitor despite moving it to primary monitor (2 monitor set up).

- [ ] Bug: App Appears on the Wrong Screen #604 

> While using a television as a second monitor, the volume flyout switches its default location to that monitor after the screen turns off (my current setting is to turn the screen off after 10 minutes).

- [ ] Volume flyout changes default to second monitor after screen turns off #663

> Currently, if you have a setup with two or more monitors on your computer, the program forces you to select a fixed monitor to show the flyouts. This is a bit unintuitive, as when you have multiple monitors, it'll be most likely that you're watching the one that has either window or cursor focus.
Describe the solution you'd like:
To have the flyout appear dynamically on the monitor that has focus, preferably according to the currently active window.
